on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test -v -cover -ldflags '-s -w -X main.version=test' ./...
